#!/bin/bash
# DO NOT EDIT THIS FILE BECAUSE IT IS AUTOMATICALLY GENERATED THROUGH ANSIBLE
echo "Resetting rules ..."
iptables --flush
iptables --delete-chain
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -F
iptables -t mangle -F
iptables -F
iptables -X

# default policy
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD ACCEPT

# accept local
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# output (general)
iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT  # dns
iptables -A OUTPUT -p udp --dport 123 -j ACCEPT  # ntp
iptables -A OUTPUT -p tcp --dport {{ openwisp2_iptables_ssh_port }} -j ACCEPT  # ssh
iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT  # web
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT  # web-ssl
iptables -A OUTPUT -p tcp --dport 9418 -j ACCEPT  # git

# input (general)
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -p tcp --dport {{ openwisp2_iptables_ssh_port }} -j ACCEPT  # ssh
{% if openwisp2_iptables_input_http %}
iptables -A INPUT -p tcp --dport 80 -j ACCEPT  # web
{% endif %}
{% if openwisp2_iptables_input_https %}
iptables -A INPUT -p tcp --dport 443 -j ACCEPT  # web-ssl
{% endif %}

# allow ICMP and traceroute
iptables -A OUTPUT -p icmp -j ACCEPT
iptables -A OUTPUT -p udp --dport 33434:33524 -m state --state NEW -j ACCEPT

# rules for VPN servers
{% for rule in openwisp2_iptables_vpn_rules %}
iptables -A INPUT -p {{ rule.protocol }} --dport {{ rule.port }} -j ACCEPT
iptables -A OUTPUT -o {{ rule.interface }} -j ACCEPT  # vpn
# allow ICMP on vpn interface
iptables -A INPUT -p icmp -i {{ rule.interface }} -j ACCEPT
iptables -A OUTPUT -p icmp -o {{ rule.interface }} -j ACCEPT
# deny internet traffic through management tunnel
iptables -A FORWARD -p all -i {{ rule.interface }} -j DROP
{% endfor %}

{% if openwisp2_iptables_iperf_port %}
# open port for Iperf3 server
iptables -A INPUT -p tcp --dport {{ openwisp2_iptables_iperf_port }} -j ACCEPT
iptables -A INPUT -p udp --dport {{ openwisp2_iptables_iperf_port }} -j ACCEPT
iptables -A OUTPUT -p tcp --dport {{ openwisp2_iptables_iperf_port }} -j ACCEPT
iptables -A OUTPUT -p udp --dport {{ openwisp2_iptables_iperf_port }} -j ACCEPT
{% endif %}

{% if openwisp2_iptables_owlp_internet_mode_port %}
# open port for OWLP internet mode
iptables -A INPUT -p tcp --dport {{ openwisp2_iptables_owlp_internet_mode_port }} -j ACCEPT
iptables -A INPUT -p udp --dport {{ openwisp2_iptables_owlp_internet_mode_port }} -j ACCEPT
{% endif %}

{% for port in openwisp2_iptables_freeradius_ports %}
{% for ip_address in openwisp2_iptables_freeradius_destinations %}
# open ports for FreeRADIUS
iptables -A INPUT -p udp --destination {{ ip_address }} --dport {{ port }} -j ACCEPT
{% endfor %}
iptables -A OUTPUT -p udp --dport {{ port }} -j ACCEPT
{% endfor %}

{% for port in openwisp2_iptables_smtp_ports %}
# open ports for SMTP
iptables -A INPUT -p tcp --dport {{ port }} -j ACCEPT
iptables -A OUTPUT -p tcp --dport {{ port }} -j ACCEPT
{% endfor %}

{% if openwisp2_iptables_wireguard_flask_port %}
# open port for WireGuard Flask app
iptables -A INPUT -p tcp --source {{ openwisp2_iptables_wireguard_flask_src_ips | join(',') }} --dport {{ openwisp2_iptables_wireguard_flask_port }} -j ACCEPT
iptables -A OUTPUT -p tcp --destination {{ openwisp2_iptables_wireguard_flask_src_ips | join(',') }} --dport {{ openwisp2_iptables_wireguard_flask_port }} -j ACCEPT
{% endif %}

{% if openwisp2_iptables_additional_rules %}
# ADDITIONAL RULES
{% for rule in openwisp2_iptables_additional_rules %}
{{ rule }}
{% endfor %}
{% endif %}
